[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/sql-wasm.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Access-Control-Allow-Origin = "*"
